version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: futures_bot
    volumes:
      - postgres_data_futures_bot:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data_futures_bot:
