"""init

Revision ID: 6cc65f5e768f
Revises: 
Create Date: 2025-05-24 16:05:59.726835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc65f5e768f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('value_tokens', sa.Float(), nullable=False),
    sa.Column('order_type', sa.Enum('long', 'short', name='ordertype'), nullable=False),
    sa.Column('price_open', sa.Float(), nullable=False),
    sa.Column('price_tp', sa.Float(), nullable=False),
    sa.Column('price_sl', sa.Float(), nullable=False),
    sa.Column('price_close', sa.Float(), nullable=True),
    sa.Column('leverage', sa.Float(), nullable=False),
    sa.Column('open_at', sa.DateTime(), nullable=True),
    sa.Column('tp_at', sa.DateTime(), nullable=True),
    sa.Column('sl_at', sa.DateTime(), nullable=True),
    sa.Column('close_at', sa.DateTime(), nullable=True),
    sa.Column('orderId_open', sa.String(), nullable=False),
    sa.Column('orderId_tp', sa.String(), nullable=True),
    sa.Column('orderId_sl', sa.String(), nullable=True),
    sa.Column('orderId_close', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
