"""init

Revision ID: f6b289d5f723
Revises: 6cc65f5e768f
Create Date: 2025-05-24 19:36:34.223704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b289d5f723'
down_revision: Union[str, None] = '6cc65f5e768f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('reverse', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'reverse')
    # ### end Alembic commands ###
